function data = importLabels(workbookFile, sheetName, range)
%importLabels Import data from a spreadsheet
%   DATA = importLabels(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as a
%   string array.
%
%   DATA = importLabels(FILE,SHEET) reads from the specified worksheet.
%
%   DATA = importLabels(FILE,SHEET,RANGE) reads from the specified worksheet
%   and from the specified RANGE. Specify RANGE using the syntax
%   'C1:C2',where C1 and C2 are opposing corners of the region.%
% Example:
%   Samplephenotyped = importLabels('Sample phenotyped.xlsx','Grid for tray','A1:P21');
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2018/03/09 09:28:52

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If no range is specified, read all data
if nargin <= 2 || isempty(range)
    range = 'A1:V15';
end

%% Import the data
[~, ~, data] = xlsread(workbookFile, sheetName, range);

data = string(data);
data(ismissing(data)) = 'N/A';
data = regexprep(data,'\.','');
