function results = myimfcn(im)
%Image Processing Function
%
% IM      - Input image.
% RESULTS - A scalar structure with the processing results.
%

%--------------------------------------------------------------------------
% Auto-generated by imageBatchProcessor App. 
%
% When used by the App, this function will be called for every input image
% file automatically. IM contains the input image as a matrix. RESULTS is a
% scalar structure containing the results of this processing function.
%
%--------------------------------------------------------------------------



% Replace the sample below with your code----------------------------------

if(size(im,3)==3)
    % Convert RGB to grayscale
    imgray = im(:,:,3);
else
    imgray = im;
end
bwBright = vesselness2D(im, 1:1:3, [1;1], 1, true);
bwDark = fibermetric(imgray,20, 'ObjectPolarity', 'bright','StructureSensitivity',20);
results.input = im;
results.imgray = imgray;
results.Vessel     = bwBright;
results.bwDark     = bwDark;


%--------------------------------------------------------------------------
